### ISSUE TITLE
Add check for "message me for more info"

### ISSUE THREAD

**Issue by ZacSweers** [ZacSweers/FB_Mod_Bot#4]
This pretty much goes explicitly against the group rules. They should post details rather than purposefully leave them out.

`message me for (more) details/info/information/pics/pictures`

can be done with a regex, the "more" part might be overkill. Might also want to file this under a new category of "advice" in the warning comment, rather than a straight warning.

**Comment by rob0rt** [comment]
I think having this check in place is a good idea, but it might be good to check against some other criteria before flagging them for this. Possibly check to see if their post is over a certain character length (longer then the current check for 200 characters), in case they've already provided ample information but they're just offering extra. Having the bot comment something like

```
I see you're requesting people contact you for additional information. 
It is suggested that you put enough information in your post for people 
to get an idea of what you are look for.
```

might discourage this behavior. As well, you'd have to have a fairly strong regex here, as opposed to the others which are more fuzzy, in the event the person is trying to say "message me if you're interested" or something of that sort.

**Comment by ZacSweers** [comment]
Bro have you seen my regexes
